# Generated by Django 6.0.7 on 2026-08-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPayment',
        ),
    ]
