# Generated by Django 6.0.7 on 2026-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_orderpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='state_governorates',
            field=models.CharField(choices=[('Cairo', 'Cairo'), ('Giza', 'Giza'), ('Alexandria', 'Alexandria'), ('Dakahlia', 'Dakahlia'), ('Red Sea', 'Red Sea'), ('Beheira', 'Beheira'), ('Fayoum', 'Fayoum'), ('Gharbia', 'Gharbia'), ('Ismailia', 'Ismailia'), ('Menofia', 'Menofia'), ('Minya', 'Minya'), ('Qalyubia', 'Qalyubia'), ('New Valley', 'New Valley'), ('Suez', 'Suez'), ('Aswan', 'Aswan'), ('Assiut', 'Assiut'), ('Beni Suef', 'Beni Suef'), ('Port Said', 'Port Said'), ('Damietta', 'Damietta'), ('Sharkia', 'Sharkia'), ('South Sinai', 'South Sinai'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Matrouh', 'Matrouh'), ('Luxor', 'Luxor'), ('Qena', 'Qena'), ('North Sinai', 'North Sinai'), ('Sohag', 'Sohag')], max_length=250, null=True),
        ),
    ]
