# Generated by Django 6.0.7 on 2026-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_state_governorates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=250),
        ),
    ]
