# Generated by Django 6.0.7 on 2026-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=250),
        ),
    ]
